/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleList: typeof import('./components/UI/articleListUI/ArticleList.vue')['default']
    AsideRouter: typeof import('./components/AsideRouter/AsideRouter.vue')['default']
    AsideRouterTree: typeof import('./components/UI/routerUI/AsideRouterTree.vue')['default']
    AsideRouterUI: typeof import('./components/UI/routerUI/AsideRouterUI.vue')['default']
    Banner: typeof import('./components/Banner/Banner.vue')['default']
    CardUI: typeof import('./components/UI/cardUI/cardUI.vue')['default']
    GeneralForm: typeof import('./components/LoginRegister/LRForms/GeneralForm/GeneralForm.vue')['default']
    HomeForm: typeof import('./components/LoginRegister/LRForms/HomeForm.vue')['default']
    InputUI: typeof import('./components/UI/InputUI/InputUI.vue')['default']
    LoginBtn: typeof import('./components/LoginRegister/LRForms/SignBtns/LoginBtn.vue')['default']
    Logo: typeof import('./components/Banner/Logo/Logo.vue')['default']
    PWLogin: typeof import('./components/LoginRegister/LRForms/LoginForms/PWLogin.vue')['default']
    RectShow: typeof import('./components/RectShow/RectShow.vue')['default']
    ReturnGeneralBtn: typeof import('./components/LoginRegister/LRForms/SignBtns/ReturnGeneralBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Banner/Search/Search.vue')['default']
    Skeleton: typeof import('./components/Skeleton/Skeleton.vue')['default']
    SkeletonRect: typeof import('./components/Skeleton/SkeletonRect.vue')['default']
    SMSLogin: typeof import('./components/LoginRegister/LRForms/LoginForms/SMSLogin.vue')['default']
    SwitchLoginBtn: typeof import('./components/Banner/LoginBtn/SwitchLoginBtn.vue')['default']
    TitleUI: typeof import('./components/UI/titleUI/titleUI.vue')['default']
    TopRouter: typeof import('./components/TopRouter/TopRouter.vue')['default']
    TopRouterUI: typeof import('./components/UI/routerUI/TopRouterUI.vue')['default']
    Welcome: typeof import('./components/LoginRegister/Welcome/Welcome.vue')['default']
    WriteBtn: typeof import('./components/Banner/WriteBtn/WriteBtn.vue')['default']
  }
}
